[Settings]
; vk key
iMenuOpenKey = 0xC0
; changes game updater thing
iOverwriteConstantFPS = 15
; slow motion spell/effect targets everything, use this 
; with updated constantfps to have smooth original free camera - else
; ignore
bSlowMotionEveywhere = false

; built in windowed mode
bUseBuiltInWindowedMode = false
; default window resolution
iDefaultXRes = 1024
iDefaultYRes = 768

; vk key
iFreeCameraKeyForward=104
iFreeCameraKeyBack=98
iFreeCameraKeyLeft=100
iFreeCameraKeyRight=102
iFreeCameraKeyUp=103
iFreeCameraKeyDown=97